ADD_PORTFOLIO_FAILED = "Не удалось добавить достижение"
ADD_PORTFOLIO_SUCCESS = "Достижение добавлено"
PORTFOLIO_GET_EXCEPTION = "Не удалось получить достижение"
PORTFOLIO_UPD_EXCEPTION = "Не удалось отредактировать достижение"
PORTFOLIO_NOT_FOUND = "Достижение не найдено"
DELETE_PORTFOLIO = "Достижение удалено"
DELETE_PORTFOLIO_EXCEPTION = "Не удалось удалить портфолио"
