ADD_ACTIVITY_FAILED = "Деятельность не удалось добавить"
ADD_STATUS_ID_EXCEPTION = "Такого статуса нет"
ASTATUSES_EXCEPTION = "Не удалось получить статусы"
ASTATUSES_NOT_FOUND = "Статусы не найдены"

DIRECTIONS_EXCEPTION = "Не удалось получить направления"
DIRECTIONS_NOT_FOUND = "Направления не найдены"

ACTIVITIES_NOT_FOUND = "Деятельности не найдены"
ACTIVITY_NOT_FOUND = "Проект не найден"
ACTIVITIES_EXCEPTION = "Не удалось получить деятельности"
ACTIVITY_EXCEPTION = "Не удалось получить проект"
UPDATE_ACTIVITY_EXCEPTION = "Не удалось изменить проект"
UPDATE_ACTIVITY_SUCCESS = "Проект изменен"
DELETE_ACTIVITY = "Проект удален"
DELETE_ACTIVITY_EXCEPTION = "Не удалось удалить проект"
INVATION_EXCEPTION = "Не удалось отправить приглашение"
INVATION_EXIST = "Приглашение или заявка уже существует"
INVATION_SUCCEESS = "Приглашение отправлено"
REQUEST_SUCCEESS = "Заявка отправлено"
REQUEST_EXCEPTION = "Не удалось отправить заявку"
DELETE_REQ_EXCEPTION = "Не удалось удалить заявку"
DELETE_REQ_SUCCESS = "Заявка удалена"
DELETE_INV_SUCCESS = "Приглашение удалено"
DELETE_INV_EXCEPTION = "Не удалось удалить приглашение"

REQ__SUCCESS = "Заявка отклонена"
INV__SUCCESS = "Приглашение отклонено"
REQ__EXCEPTION = "Не удалось отклонить заявку"
INV__EXCEPTION = "Не удалось отклонить приглашение"
REQ_EXCEPTION = "Не удалось получить приглашение/заявку"
REQS_EXCEPTION = "Не удалось получить приглашения/заявки"

REQT_SUCCESS = "Заявка одобрена"
INVT_SUCCESS = "Приглашение одобрено"
REQT_EXCEPTION = "Не удалось одобрить заявку"
INVT_EXCEPTION = "Не удалось одобрить приглашение"

EXIT_SUCCESS = "Группа вышла из проекта"
KICK_SUCCESS = "Группа выгната из проекта"
EXIT_EXCEPTION = "Не удалось выйти из проекта"
KICK_EXCEPTION = "Не удалось выгнать группу из проекта"

TASK_ADDED = "Задача добавлена"
ADD_TASK_FAILED = "Задачу не удалось добавить"
TASK_EXCEPTION = "Не удалось получить задачу"
UPDATE_TASK_EXCEPTION = "Не удалось изменить задачу"
TASK_UPDATED = "Задача изменена"
TASK_NOT_FOUND = "Задача не найдена"
DELETE_TASK = "Задача удалена"
DELETE_TASK_EXCEPTION = "Не удалось удалить задачу"
ASS_ADDED = "Задача назначена пользователю"
ASS_EXCEPTION = "Задачу не удалось назначить пользователю"
ASS_NOT_FOUND = "Назначение задачи не найдено"
ASS_DELETED = "Назначение задачи пользователю удалено"
ASS_DELETED_EXCEPTION = "Не удалось удалить назначение задачи пользователю"
UPDATE_TASK_STATUS_EXCEPTION = "Не удалось изменить статус задачу"
TASK_STATUS_UPDATED = "Статус задачи изменен"
TASKS_EXCEPTION = "Не удалось получить задачи"
TASKS_NOT_FOUND = "Задачи не найдены"
TASK_ASSIGNED_ALREADY = "Задача уже назначена"

ACTIVITY_POST = """# Добро пожаловать

Добро пожаловать в наш новый проект **{0}**! Мы рады приветствовать каждого участника и готовы вместе создавать что-то удивительное. Давайте вместе воплощать свои идеи и делать этот проект незабываемым!"""
INV = "Вашей группе «{0}» отправлено приглашение в проект «{1}»"
REQ = "Группа «{0}» отправила заявку в проект «{1}»"
REQ_APP = "Ваша заявка в проект «{0}» одобрена"
REQ_REJ = "Ваша заявка в проект «{0}» отклонена"
INV_APP = "Ваше приглашение в проект «{0}» одобрено"
INV_REJ = "Ваше приглашение в проект «{0}» отклонено"
GROUP_EXIT = "Группа «{0}» вышла из проекта «{1}»"
GROUP_KICK = "Вашу группу «{0}» выгнали из проекта «{1}»"
TASK_ASS = "Вам назначили задачу «{0}» в проекте «{1}»"