DEFAULT_LIMIT = 100
DEFAULT_OFFSET = 0
VALUE_NOT_LESS = 0

NAME_SCHEMA_ACTIVITY = "activities"
NAME_SCHEMA_GROUP = "groups"
NAME_SCHEMA_POST = "posts"
NAME_SCHEMA_USER='users'

FILE_ENV = ".env"
MAIN_QUEUE_NAME_CELERY = "diplom-tasks"
