from src.group.schemas.group_create import *
from src.group.schemas.group_role import *
from src.group.schemas.group_type import *
from src.group.schemas.group_user2 import *
from src.group.schemas.full_group import *
from src.group.schemas.group import *
from src.group.schemas.group2_user import *
from src.group.schemas.sub import *
from src.group.schemas.vacancy_create import *
from src.group.schemas.vacancy import *
from src.group.schemas.vacancy_user import *
from src.group.schemas.response import *
from src.group.schemas.full_group_n import *
from src.group.schemas.vacancy_vacancy_user import *
