ACTIVITIES_EXCEPTION="Не удалось получить проекты"
ACTIVITIES_SUCCESS="Проекты проиндексированы"
GROUPS_SUCCESS="Группы проиндексированы"
GROUPS_EXCEPTION="Не удалось получить группы"
POSTS_SUCCESS="Новости проиндексированы"
POSTS_EXCEPTION="Не удалось получить новости"
USERS_SUCCESS="Пользователи проиндексированы"
USERS_EXCEPTION="Не удалось получить пользователей"