ADD_MSG_FAILED = "Не удалось сохранить сообщение"
ACT_FAILED = "Не удалось получить проект"
MSGS_EXCEPTION = "Не удалось получить сообщения"
MSGS_NOT_FOUND = "Сообщения не найдены"
DELETE_MSG_EXCEPTION = "Сообщение не удалось удалить"
MSG_FAILED = "Не удалось получить сообщение"
CONNECTED_SUCCESS = "Соединение открыто"