"""some changes

Revision ID: 70c392f1b0a7
Revises: 3d5cf6ecd708
Create Date: 2024-04-07 10:46:15.852380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70c392f1b0a7'
down_revision = '3d5cf6ecd708'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
