"""some changes

Revision ID: 5bafa7dc8174
Revises: dfd554cd6625
Create Date: 2024-03-18 21:09:38.380745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bafa7dc8174'
down_revision = 'dfd554cd6625'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activity_groups', sa.Column('status_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'activity_groups', 'activity_link_statuses', ['status_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activity_groups', type_='foreignkey')
    op.drop_column('activity_groups', 'status_id')
    # ### end Alembic commands ###
