"""some changes

Revision ID: 994be5318665
Revises: abb665627dc6
Create Date: 2024-03-25 20:44:52.777782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994be5318665'
down_revision = 'abb665627dc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
