"""some changes

Revision ID: 30379d7461f4
Revises: a0e63be45e93
Create Date: 2024-04-20 17:11:41.516900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '30379d7461f4'
down_revision = 'a0e63be45e93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_abstracts', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_abstracts', 'is_active')
    # ### end Alembic commands ###
