"""some changes

Revision ID: 571672364fce
Revises: 5e6dcf079097
Create Date: 2024-03-20 10:10:23.705785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571672364fce'
down_revision = '5e6dcf079097'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancies', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancies', 'is_active')
    # ### end Alembic commands ###
