"""some changes

Revision ID: 5158d5a6431d
Revises: 60514b9de5bd
Create Date: 2024-03-24 16:40:29.242235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5158d5a6431d'
down_revision = '60514b9de5bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('requests', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('requests', 'activity_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('requests', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('requests', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('requests', 'activity_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('requests', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
