"""some changes

Revision ID: c1eac22a657f
Revises: d18b0c558538
Create Date: 2024-04-23 21:37:51.684471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1eac22a657f'
down_revision = 'd18b0c558538'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_types', sa.Column('placeholder', sa.String(length=255), nullable=True))
    op.add_column('portfolios', sa.Column('note', sa.Text(), nullable=True))
    op.add_column('portfolios', sa.Column('value', sa.Text(), nullable=True))
    op.drop_column('portfolios', 'text')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('text', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('portfolios', 'value')
    op.drop_column('portfolios', 'note')
    op.drop_column('portfolio_types', 'placeholder')
    # ### end Alembic commands ###
