"""some changes

Revision ID: cb317c841447
Revises: 4fdc6c21e1a1
Create Date: 2024-04-07 12:58:57.981621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb317c841447'
down_revision = '4fdc6c21e1a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_type_id_fkey', 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'post_types', ['type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key('posts_type_id_fkey', 'posts', 'group_types', ['type_id'], ['id'])
    # ### end Alembic commands ###
