"""some changes

Revision ID: 21174d72f8d0
Revises: 42f579500bf3
Create Date: 2024-04-18 21:48:43.522070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21174d72f8d0'
down_revision = '42f579500bf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
