"""Edit groups

Revision ID: 0ed6a2862045
Revises: a3818abd93a1
Create Date: 2024-03-07 19:25:39.290673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ed6a2862045'
down_revision = 'a3818abd93a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('username', sa.String(length=255), nullable=True))
    op.drop_constraint('groups_altername_key', 'groups', type_='unique')
    op.create_unique_constraint(None, 'groups', ['username'])
    op.drop_column('groups', 'altername')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('altername', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'groups', type_='unique')
    op.create_unique_constraint('groups_altername_key', 'groups', ['altername'])
    op.drop_column('groups', 'username')
    # ### end Alembic commands ###
