"""some changes

Revision ID: 60514b9de5bd
Revises: 0bda0ef869f5
Create Date: 2024-03-24 10:55:15.202458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60514b9de5bd'
down_revision = '0bda0ef869f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contact_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['contact_id'], ['contacts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_activities')
    # ### end Alembic commands ###
