"""some changes

Revision ID: ca8a8d69c055
Revises: 7d9a99a9e100
Create Date: 2024-03-21 18:09:54.398707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca8a8d69c055'
down_revision = '7d9a99a9e100'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag_vacancies', sa.Column('level_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tag_vacancies', 'tag_levels', ['level_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_vacancies', type_='foreignkey')
    op.drop_column('tag_vacancies', 'level_id')
    # ### end Alembic commands ###
