"""some changes

Revision ID: 37808acb9df3
Revises: 21174d72f8d0
Create Date: 2024-04-18 23:29:52.071764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37808acb9df3'
down_revision = '21174d72f8d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
