"""some changes

Revision ID: 35a288670069
Revises: acaac38d8f0b
Create Date: 2024-04-29 18:49:04.112717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35a288670069'
down_revision = 'acaac38d8f0b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('directions', sa.Column('icon', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('directions', 'icon')
    # ### end Alembic commands ###
