"""some changes

Revision ID: 0bda0ef869f5
Revises: ca8a8d69c055
Create Date: 2024-03-22 00:01:38.328080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bda0ef869f5'
down_revision = 'ca8a8d69c055'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vacancy_users', sa.Column('is_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vacancy_users', 'is_approved')
    # ### end Alembic commands ###
