"""some changes

Revision ID: 296b6c4f6d32
Revises: cd5d5279e2c2
Create Date: 2024-03-19 21:49:07.720769

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '296b6c4f6d32'
down_revision = 'cd5d5279e2c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_task_statuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('activity_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('creater_id', sa.Integer(), nullable=True),
    sa.Column('activity_id', sa.Integer(), nullable=True),
    sa.Column('status_id', sa.Integer(), nullable=True),
    sa.Column('deadline', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('materials', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ),
    sa.ForeignKeyConstraint(['creater_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['activity_task_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_task_assignments',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['task_id'], ['activity_tasks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'task_id')
    )
    op.add_column('activities', sa.Column('group_id', sa.Integer(), nullable=True))
    op.add_column('activities', sa.Column('fields', sa.JSON(), nullable=True))
    op.create_foreign_key(None, 'activities', 'groups', ['group_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'fields')
    op.drop_column('activities', 'group_id')
    op.drop_table('activity_task_assignments')
    op.drop_table('activity_tasks')
    op.drop_table('activity_task_statuses')
    # ### end Alembic commands ###
