"""some changes

Revision ID: acaac38d8f0b
Revises: 6bfa39bf0275
Create Date: 2024-04-29 17:25:46.073761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acaac38d8f0b'
down_revision = '6bfa39bf0275'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('direction_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'activities', 'directions', ['direction_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'activities', type_='foreignkey')
    op.drop_column('activities', 'direction_id')
    # ### end Alembic commands ###
