"""some changes

Revision ID: e861797d2e70
Revises: 7a640061c74c
Create Date: 2024-03-31 09:57:30.558740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e861797d2e70'
down_revision = '7a640061c74c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_statuses', 'is_change')
    op.add_column('activity_task_statuses', sa.Column('is_change', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activity_task_statuses', 'is_change')
    op.add_column('activity_statuses', sa.Column('is_change', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
