"""some changes

Revision ID: 215f40374856
Revises: 59e3560eec8e
Create Date: 2024-04-22 10:56:22.546597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215f40374856'
down_revision = '59e3560eec8e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_readed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_readed')
    # ### end Alembic commands ###
