"""some changes

Revision ID: 3d5cf6ecd708
Revises: f7b3caf557a8
Create Date: 2024-04-06 09:55:05.634200

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5cf6ecd708'
down_revision = 'f7b3caf557a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_creater_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'creater_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('creater_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_creater_id_fkey', 'posts', 'users', ['creater_id'], ['id'])
    # ### end Alembic commands ###
