"""some changes

Revision ID: 20eb4086e4ee
Revises: 37808acb9df3
Create Date: 2024-04-18 23:35:56.572883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20eb4086e4ee'
down_revision = '37808acb9df3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
